- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
- config/GMAO_Shared.sparse
Small changes to GOCART2G, to eliminate the dependency on the `m_StrTemplate` provided by  `GMAO_Shared/GMAO_mpeu` in favor of the replacement in `MAPL_StringTemplate` provided by MAPL.
Note that I have not tested this yet, so I ask @gmao-esherman to please test this change before this is accepted.
> Remove mpeu dependency from GOCART2G

- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
In running GOCART2G tests within NOAA's UFS system @rmontuoro discovered an error in the `PET.ESMF_LogFiles` related to reading the `BANDS:` option from the MAPL config.
This fixes this issue along with several related `rc` code errors found in GOCART2G's children.
> Bug fix for reading bands from RC files

- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
- Process_Library/GOCART2G_Process.F90
@gmao-esherman reported two errors resulting from the `rc` handling PR #31, due to it catching non-zero return codes. Namely, the tracebacks:
```
pe=00010 FAIL at line=00832 NI2G_GridCompMod.F90 <status=-858993460>
pe=00025 FAIL at line=01092 SU2G_GridCompMod.F90 <status=100>
```
The first was cased by an uninitialized value for the `rc` in the process library. While the second is due to the inclusion of a gas phase in the SU bins, so there shouldn't be any settling for that bin anyways.
> GOCART errors

- CHANGELOG.md
- ESMF/UFS/Aerosol_Cap.F90
- ESMF/UFS/Aerosol_Comp_Mod.F90
This PR introduces changes to the UFS/NUOPC cap to compute and export total diagnostic PM2.5 and PM10 for the UFS weather model. These quantities are computed according to formulas provided by @amdasilva.
The changes have been tested within UFS-GOCART on NOAA's Hera platform.
> Compute and export total PM2.5 and PM10 for UFS

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridComp_DU.rc
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_StateSpecs.rc
- ESMF/UFS/Aerosol_Cap.F90
- ESMF/UFS/Aerosol_Comp_Mod.F90
- Process_Library/GOCART2G_Process.F90
This PR implements the FENGSHA dust scheme as an option for the GOCART dust component.
The FENGSHA scheme, developed at NOAA/ARL, is added to the GOCART process library along with few auxiliary procedures. It requires the additional input fields below, provided as surface map files via ExtData:
```
FRCLAY                '1'  Y E - none none clayfrac     ExtData/Dust/FENGSHA_DUST_INPUTS_v0.6.nc
FRSAND                '1'  Y E - none none sandfrac     ExtData/Dust/FENGSHA_DUST_INPUTS_v0.6.nc
FRSILT                '1'  Y E - none none siltfrac     ExtData/Dust/FENGSHA_DUST_INPUTS_v0.6.nc
SSM                   '1'  Y E - none none ssm          ExtData/Dust/FENGSHA_DUST_INPUTS_v0.6.nc
RDRAG                 '1'  Y E - none none drag_part    ExtData/Dust/FENGSHA_DUST_INPUTS_v0.6.nc
UTHRES …
```
> Implement NOAA/ARL FENGSHA dust scheme

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- components.yaml
This PR updates the CircleCI to use the `large` resource due to resumption of paid plan.
In order to debug why this was failing at first, I also updated the `components.yaml` to something that is usable on discover for debugging.
> Update CircleCI to use large, and update components.yaml

- CHANGELOG.md
- CMakeLists.txt
- ESMF/CMakeLists.txt
- ESMF/UFS/CMakeLists.txt
- ESMF/UFS/cmake/README.md
- ESMF/UFS/cmake/esma.cmake
- ESMF/UFS/cmake/ufs_ecbuild.cmake
- ESMF/UFS/cmake/ufs_ecbuild_declare_project.cmake
- ESMF/UFS/cmake/ufs_ecbuild_install_project.cmake
- ESMF/UFS/cmake/ufs_esma.cmake
- ESMF/UFS/cmake/ufs_esma_add_library.cmake
- ESMF/UFS/cmake/ufs_esma_add_subdirectories.cmake
- ESMF/UFS/cmake/ufs_esma_generate_automatic_code.cmake
- ESMF/UFS/cmake/ufs_esma_set_this.cmake
This PR introduces  the following set of changes, which are needed for integration with the UFS weather model:
- The `BUILD_UFS` CMake flag is renamed `UFS_GOCART` to avoid confusion in the UFS build system
- The `UFS` CMake library target is renamed `UFS_Aerosols` to prevent conflicts within the UFS build system
- A minimal set of custom CMake macros and functions is included to remove GOCART's dependency on ecBuild and ESMA_cmake when building with `UFS_GOCART=ON`. This was required by UFS code managers.
- Relaxed PFLOGGER dependency requirement outside Baselibs, since the UFS builds without pFlogger.
All changes have been tested on the NOAA RDHPCS Hera platform within the UFS weather model.
> Updates for UFS integration

- CHANGELOG.md
- ESMF/UFS/Aerosol_Comp_Mod.F90
This PR introduce minor changes to the UFS Aerosols component that are required in order to build with GNU 9.2.0
> Fix build issue with GNU 9.2.0

- .circleci/config.yml
- CHANGELOG.md
This PR updates the CI to use Baselibs 6.2.8. This is futureproofing for MAPL development which needs a newer version of gFTL that doesn't affect GEOS as a whole yet.
This is still zero-diff for GEOS.
This also moves to use GCC 11.2 which is the current GCC for GEOS. (I'll look at adding Intel soon)
> Update CI to Baselibs 6.2.8 and GCC 11.2

- CHANGELOG.md
- Process_Library/GOCART2G_Process.F90
This PR implements an improvement to the streamwise sediment flux density formulation used by the FENGSHA dust scheme, based on recent work by Webb et al. (_Aeolian Research_, Vol. 42, 2020, 100560, https://doi.org/10.1016/j.aeolia.2019.100560).
The changes have been tested on NOAA RDHPCS platforms and validated by NOAA/ARL.
> Update sediment flux formulation in FENGSHA dust scheme

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridComp_ExtData.rc
This PR fixes some ExtData lines for Dust by adding in a missing /.
This is zero-diff in the sense that nothing was ever using these lines (yet, seems to be for data_driven), but it is still a bug.
Closes #109 
(NOTE: I'm putting this onto `develop` instead of `main` after talking with @amdasilva. So I closed #110 and opened this.)
> Fixes #109. Correct Dust ExtData

- CHANGELOG.md
- ESMF/GOCART_GridComp/CMakeLists.txt
- components.yaml
Due to insufficient grepping on my part, some remnants of the
"not-canonical" CMake still remain. Apparently these were not necessary
changes for Spack, but they are changes that unify the CMake style of
GEOS to be more like "correct" CMake.
In this go-around, it is mainly finding `INC_ESMF` which I apparently
forgot to grep for last time (I was focused on NetCDF), and some
non-canonical OpenMP calls.
See https://github.com/GEOS-ESM/GEOSgcm/issues/387 for the meta-issue.
> Updates for Spack Support, Round 2

- .github/CODEOWNERS
- CHANGELOG.md
- components.yaml
This PR updates the `CODEOWNERS` file so that PR approvals here are less onerous. Only the CI and weird CCPP/UFS directories will need approval from non-aerosol team members.
NOTE: I think this will not truly take effect until this change is in `main` due to the way GitHub works. (Only the `CODEOWNERS` on `main` matters to GitHub. Annoying, but it's how they do things.)
---
ETA: I've also updated `components.yaml` to match that of GEOSgcm v10.22.1. The main thing is to get MAPL 2.19.0 which is needed for the new AGC code that is in `develop`.
> Update CODEOWNERS and update components to match GEOSgcm v10.22.1

- CHANGELOG.md
- CMakeLists.txt
- Process_Library/GOCART2G_Process.F90
Closes #130 
TL;DR: This PR fixes the "changing klid halts GOCART" issue seen by @wmputman. 
My testing shows that it is zero-diff if klid is set to 0.01 (aka k=1), and lets the model run at other klid values.
Runs with:
---
The solution was found by running with Intel in Debug mode where it pointed to line 1412:
https://github.com/GEOS-ESM/GOCART/blob/4d4f27c51f49ccebb2df5e167582d033eea4d0d4/Process_Library/GOCART2G_Process.F90#L1400-L1414
The issue is that `vsettle` is filled by `Chem_CalcVsettle` but only for `vsettle(:,:,klid:km)`. But then this line:
```fortran
vsettle = max(1.0e-9, vsettle - v_upwardMaring)
```
operates on *all* of `vsettle`. Since `vsettle` was only allocated and never initialized to anything, boom.
To be safe, I'm initializing *all* local allocatable arrays that I …
> Fixes #130. Initialize allocatable variables in Process Library

- CHANGELOG.md
- CMakeLists.txt
- Process_Library/GOCART2G_Process.F90
Hand merge gitflow due to conflict.
> GitFlow: Hand merge main into develop 2022-04-28

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/GOCART2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_StateSpecs.rc
Fixes #140 
Also needs this PR from chem as well to fix the issue:
https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/182
> Hotfix: fixes #140

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90
@amdasilva , This is for the issue #136.  I am not sure if it a good fix. Please verify it.
> fix bug in getAerosolSum

- CHANGELOG.md
- Process_Library/GOCART2G_Process.F90
This fixes issue #156 
There continues that should have been cycles in the GOCART2G process library. This was causing the loop not to break when it should have and an out of bounds error to occur.
> Fixes #156

- .circleci/config.yml
- CHANGELOG.md
- components.yaml
This PR does two things:
1. Updates the CI to use the new v1 orb like (most of) the rest of GEOS
2. Updates the `components.yaml` to match GEOSgcm v10.22.4
> Closes #161. Update CI and components.yaml

- .circleci/config.yml
- CHANGELOG.md
- ESMF/GOCART2G_GridComp/GA_Environment/CMakeLists.txt
- ESMF/GOCART2G_GridComp/SU2G_GridComp/CMakeLists.txt
- ESMF/Shared/CMakeLists.txt
This PR is an attempt to fix an issue seen by our UFS colleagues building GOCART, see:
#174 
#176 
I have tested this and it is zero-diff since, well, the model built and I only changed CMake.
I guess what I need is @benjamin-cash or someone on the UFS side to test and see if it fixes their issue.
> Fixes #176. Add extra esmf dependencies to CMake

- .circleci/config.yml
- CHANGELOG.md
- CMakeLists.txt
- ESMF/UFS/Aerosol_Internal_Mod.F90
Closes #184 
This removes some unneeded `find_package` calls for GFE libraries. These are needed by MAPL not GOCART and so are redundant here (and as @rmontuoro pointed out, bad).
This also adds a new CI test to build GOCART like UFS.
> Fixes #184. Remove unneeded GFE find_package calls

- .circleci/config.yml
- CHANGELOG.md
Due to recent changes in the GEOSgcm_App, we need to advance the BCs version in the CI so that the scripting for making an experiment works.
> Update CI BCs version to fix GEOSgcm run

- .circleci/config.yml
- CHANGELOG.md
- components.yaml
This PR updates the CircleCI and components to be more in line with GEOSgcm and MAPL
> Update CircleCI and components

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_StateSpecs.rc
- components.yaml
Closes #202 
With MAPL 2.34 now in GEOSgcm `main`, I feel confident about making this PR. To wit, this PR uses the updated *-expansion in MAPL's ACG to expand out the Long Name in the State Specs much like it does in the short name. Note that this is a bit different than might be expected[^compname].
Note I also changed the Internal state *-variables here:
```
*phobic | kg kg-1 | xyz  | C    | MAPL_RestartOptional | T          | DYNAMICS:TURBULENCE:MOIST | Carbonaceous Aerosol Mixing Ratio
*philic | kg kg-1 | xyz  | C    | MAPL_RestartOptional | T          | DYNAMICS:TURBULENCE:MOIST | Carbonaceous Aerosol Mixing Ratio
```
to:
```
*phobic | kg kg-1 | xyz  | C    | MAPL_RestartOptional | T          | DYNAMICS:TURBULENCE:MOIST | * Hydrophobic Aerosol Mixing Ratio
*philic | kg kg-1 | xyz  | …
```
> Fixes #202. Add * to Long Name for CA Gridded Component

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridComp_ExtData.yaml
ExtData yaml files were modified for SU, CA, and NI to add rules for persisting 2019 after the datasets end for CEDS and MERRA-2 GMI. This means that duplicate input files are no longer needed for years after 2019.
> Persist emissions after 2019 using ExtData2G

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90
> Ensure GOCART2G can run without the NI component.

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
In GOCART2G children, globalCellCountPerDim is used instead of localCellCountPerDim to dimension local arrays, leading to excessive memory wastage. Changes were made to use localCellCountPerDim.
> Issue #223 Global dimension for a local array

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_StateSpecs.rc
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_StateSpecs.rc
fixes #146
This fixes a long standing issue that one can not start and stop the model in anything less than 3 hour increments to test start/stop regression because of GOCART
I will not rehash why this occurring other than to say this is unacceptable. If you look in the issue you will see all the details. The one thing I had to do was remove ESFM alarms, the whole problem was that an alarm was made relative to the model start time which just can not be. But the problem is if the ESMF Alarm is created correctly, say at 0z of the day so that no matter when you start you get the same behavior, it does not work right as there are fundamental bugs in ESMF alarms. ESMF is aware of this and will fix it some day, but until then we must avoid using them. In it's place I made a simple function that …
> Fix 3 hourly frequency update in go-cart to allow start/stop regression in less than 3 hour chances

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90
It looks like a bug might have come into GOCART a bit ago when backscatter calculations were added. If you look at the changes here, the `totscacoefrh80` with `ocscacoefrh80` code was transformed into a *second* `totscacoefrh20` with `ocscacoefrh20` calculation.
I believe this is a bug, as the 20/80 duo exist for other species.
cc: @vbuchard
> Fix for totscacoefrh80 and OC

- CHANGELOG.md
- ESMF/GOCART2G_GridComp/CA2G_GridComp/AMIP/CA2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/NI2G_GridComp/AMIP/NI2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP/SU2G_GridComp_ExtData.yaml
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridComp_ExtData.yaml
Closes #280. Modifies the file path for CEDS anthropogenic emissions to used the revised version with a corrected seasonal cycle
> CEDS Filepath Update for G2G Develop

- CHANGELOG.md
- ESMF/Aerosol_GridComp/CMakeLists.txt
- ESMF/Apps/CMakeLists.txt
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/DU2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/GA_Environment/CMakeLists.txt
- ESMF/GOCART2G_GridComp/NI2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/SS2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/SU2G_GridComp/CMakeLists.txt
- ESMF/GOCART_GridComp/CFC_GridComp/CMakeLists.txt
- ESMF/GOCART_GridComp/CMakeLists.txt
- ESMF/GOCART_GridComp/CO2_GridComp/CMakeLists.txt
- ESMF/GOCART_GridComp/CO_GridComp/CMakeLists.txt
- ESMF/GOCART_GridComp/Rn_GridComp/CMakeLists.txt
- ESMF/Shared/CMakeLists.txt
- ESMF/UFS/CMakeLists.txt
- Process_Library/CMakeLists.txt
This PR updates the ESMF CMake target to `ESMF::ESMF` which is the correct canonical target name for ESMF. NOTE: This requires ESMF 8.6.1 or later.
This reflects the target name requested by our Spack-using colleagues and is the "right" thing to do CMake-wise. This should pass all CMake tests...
> Update ESMF CMake target to ESMF::ESMF

- CHANGELOG.md
- CMakeLists.txt
As found by @DusanJovic-NOAA in https://github.com/ufs-community/ufs-weather-model/issues/2399 my previous CMake PR (#273) worked well for us, but broke UFS. Mea culpa.
So, we add CMake to say "if `UFS_GOCART` is true, so is `GOCART_STANDALONE`"
> Fix issue between UFS build and standalone CMake

- ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP/SU2G_instance_SU.rc
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_instance_SU.rc
Degassing file path is corrected. Additionally, a safeguard has been implemented to halt model execution if the specified volcanic file does not exist for the requested date.
> SU_Volcanic: file path and protection for missing file

- .circleci/config.yml
- .github/workflows/validate_yaml_files.yml
- CHANGELOG.md
- CMakeLists.txt
- ESMF/GOCART2G_GridComp/CA2G_GridComp/CMakeLists.txt
- ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_StateSpecs.rc
- components.yaml
Per GitFlow, as #298 merged into `main` we now merge `main` into `develop`.
Done with @acollow and @vbuchard watching.
> Merge main into develop - 2025-Jan-16

- CHANGELOG.md
- Process_Library/GOCART2G_MieMod.F90
This PR reverts the change made in PR #257.    
Because 'rhod' is being pulled from 'rhop' (for relative humidity = 0), there should not be 'rhod' instead of 'rhop.' 
'rhod' looks nonexistent in file as well.
> Reverted to intended 'rhod' reading
